{{ include ".template-helper-functions" -}}
{{ if env.variant == "alpine" then ( -}}
FROM alpine:{{ .alpine.version }} AS base
{{ ) else ( -}}
FROM debian:{{ .debian.version }}-slim AS base
{{ ) end -}}

FROM base AS build

ENV VALKEY_DOWNLOAD_SHA {{ .sha256 // error("no sha256 for \(.version) (\(env.version))") }}

ADD "{{ .url }}" /valkey.tar.gz

RUN set -eux; \
	\
{{ if env.variant == "alpine" then ( -}}
	apk add --no-cache \
		coreutils \
		dpkg-dev dpkg \
		gcc \
		g++ \
		linux-headers \
		make \
		musl-dev \
		openssl-dev \
	; \
{{ ) else ( -}}
	apt-get update; \
	apt-get install -y --no-install-recommends \
		dpkg-dev \
		gcc \
		libc6-dev \
		libssl-dev \
		libsystemd-dev \
		make \
	; \
	rm -rf /var/lib/apt/lists/*; \
{{ ) end -}}
	\
	{{ if .version == "unstable" then ( -}}
		echo "Unstable Valkey version, do not compare SHA256SUM" ;\
	{{ ) else ( -}}
		echo "$VALKEY_DOWNLOAD_SHA *valkey.tar.gz" | sha256sum -c -; \
	{{ ) end -}}
	\
	mkdir -p /usr/src/valkey; \
	tar -xzf valkey.tar.gz -C /usr/src/valkey --strip-components=1; \
	rm valkey.tar.gz; \
	\
# disable Valkey protected mode [1] as it is unnecessary in context of Docker
# (ports are not automatically exposed when running inside Docker, but rather explicitly by specifying -p / -P)
	grep -E '^ *createBoolConfig[(]"protected-mode",.*, *1 *,.*[)],$' /usr/src/valkey/src/config.c; \
	sed -ri 's!^( *createBoolConfig[(]"protected-mode",.*, *)1( *,.*[)],)$!\10\2!' /usr/src/valkey/src/config.c; \
	grep -E '^ *createBoolConfig[(]"protected-mode",.*, *0 *,.*[)],$' /usr/src/valkey/src/config.c; \
# for future reference, we modify this directly in the source instead of just supplying a default configuration flag because apparently "if you specify any argument to valkey-server, [it assumes] you are going to specify everything"
# (more exactly, this makes sure the default behavior of "save on SIGTERM" stays functional by default)
	\
# https://github.com/jemalloc/jemalloc/issues/467 -- we need to patch the "./configure" for the bundled jemalloc to match how Debian compiles, for compatibility
# (also, we do cross-builds, so we need to embed the appropriate "--build=xxx" values to that "./configure" invocation)
	gnuArch="$(dpkg-architecture --query DEB_BUILD_GNU_TYPE)"; \
	extraJemallocConfigureFlags="--build=$gnuArch"; \
# https://salsa.debian.org/debian/jemalloc/-/blob/c0a88c37a551be7d12e4863435365c9a6a51525f/debian/rules#L8-23
	dpkgArch="$(dpkg --print-architecture)"; \
	case "${dpkgArch##*-}" in \
		amd64 | i386 | x32) extraJemallocConfigureFlags="$extraJemallocConfigureFlags --with-lg-page=12" ;; \
		*) extraJemallocConfigureFlags="$extraJemallocConfigureFlags --with-lg-page=16" ;; \
	esac; \
	extraJemallocConfigureFlags="$extraJemallocConfigureFlags --with-lg-hugepage=21"; \
	grep -F 'cd jemalloc && ./configure ' /usr/src/valkey/deps/Makefile; \
	sed -ri 's!cd jemalloc && ./configure !&'"$extraJemallocConfigureFlags"' !' /usr/src/valkey/deps/Makefile; \
	grep -F "cd jemalloc && ./configure $extraJemallocConfigureFlags " /usr/src/valkey/deps/Makefile; \
	\
{{ if .version == "unstable" then ( -}}
	echo "Unstable version detected — enabling USE_FAST_FLOAT"; \
	{{ if env.variant == "alpine" then ( -}}
	{{ ) else ( -}}
		apt-get update; \
		apt-get install -y --no-install-recommends g++; \
		rm -rf /var/lib/apt/lists/*; \
	{{ ) end -}}
	export BUILD_TLS=yes USE_FAST_FLOAT=yes; \
{{ ) elif ( (.version | split(".") | .[0] | tonumber) * 100 + (.version | split(".") | .[1] | tonumber) ) >= 801 then ( -}}
	echo "Version {{ .version }} is 8.1 or higher - enabling USE_FAST_FLOAT"; \
	{{ if env.variant == "alpine" then ( -}}
	{{ ) else ( -}}
		apt-get update; \
		apt-get install -y --no-install-recommends g++; \
		rm -rf /var/lib/apt/lists/*; \
	{{ ) end -}}
	export BUILD_TLS=yes USE_FAST_FLOAT=yes; \
{{ ) else ( -}}
	export BUILD_TLS=yes; \
{{ ) end -}}
{{ if env.variant == "alpine" then ( -}}
	\
{{ ) else ( -}}
	export USE_SYSTEMD=yes; \
{{ ) end -}}
	make -C /usr/src/valkey -j "$(nproc)" all; \
	make -C /usr/src/valkey install; \
	\
	serverMd5="$(md5sum /usr/local/bin/valkey-server | cut -d' ' -f1)"; export serverMd5; \
	find /usr/local/bin/valkey* -maxdepth 0 \
		-type f -not -name valkey-server \
		-exec sh -eux -c ' \
			md5="$(md5sum "$1" | cut -d" " -f1)"; \
			test "$md5" = "$serverMd5"; \
		' -- '{}' ';' \
		-exec ln -svfT 'valkey-server' '{}' ';' \
	; \
	\
	echo {{
		{
			name: "valkey-server",
			version: .version,
			params: (
				if env.variant == "alpine" then
					{
						os_name: "alpine",
						os_version: .alpine.version,
					}
				else
					{
						os_name: "debian",
						os_version: .debian.version,
					}
				end
			),
			licenses: [
				"BSD-3-Clause"
			]
		} | sbom | tostring | @sh
	}} > /usr/local/valkey.spdx.json

FROM base

ENV VALKEY_VERSION {{ .version }}

# add our user and group first to make sure their IDs get assigned consistently, regardless of whatever dependencies get added
{{ if env.variant == "alpine" then ( -}}
RUN set -eux; \
# alpine already has a gid 999, so we'll use the next id
	addgroup -S -g 1000 valkey; \
	adduser -S -G valkey -u 999 valkey
{{ ) else ( -}}
RUN set -eux; \
	groupadd -r -g 999 valkey; \
	useradd -r -g valkey -u 999 valkey
{{ ) end -}}

# runtime dependencies
{{ if env.variant == "alpine" then ( -}}
RUN set -eux; \
	apk add --no-cache \
# add tzdata for https://github.com/docker-library/redis/issues/138
		tzdata \
		# add setpriv for step down from root.
		setpriv \
		openssl \
		libgcc \
	;
{{ ) else ( -}}
RUN set -eux; \
	apt-get update; \
	apt-get install -y --no-install-recommends \
# add tzdata explicitly for https://github.com/docker-library/redis/issues/138 (see also https://bugs.debian.org/837060 and related)
		tzdata \
		{{ if .debian.version != "bookworm" then "libssl3t64" else "libssl3" end }} \
	; \
	rm -rf /var/lib/apt/lists/*
{{ ) end -}}

# Install valkey built earlier
COPY --from=build /usr/local /usr/local
RUN mkdir /data && \
	chown valkey:valkey /data && \
	mkdir -p /run/valkey && \
	chown valkey:valkey /run/valkey && \
	valkey-cli --version && \
	valkey-server --version
WORKDIR /data

COPY docker-entrypoint.sh /usr/local/bin/
ENTRYPOINT ["docker-entrypoint.sh"]

EXPOSE 6379
CMD ["valkey-server"]
